semantic_version: 19.0.5
plugins:
  - '@semantic-release/changelog@6.0.2'
  - '@semantic-release/git@10.0.1'
  - - '@codedependant/semantic-release-docker':
        dockerImage: 'itair86/israel-bank-firefly-importer'
