semantic_version: 19.0.5
plugins:
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - - '@codedependant/semantic-release-docker':
        dockerImage: 'itair86/israel-bank-firefly-importer'
