firefly:
  baseUrl: 'http://my-hosted-firefly.local'
  tokenApi: ''
banks: []
identifyMethod:
  isracard: identifier
  leumi: hash
  visaCal: hash
creditCardDesc:
  - desc: 'ל.מאסטרקרד(יש)'
    creditCard: isracard
  - desc: 'ישראכרט-י'
    creditCard: isracard
  - desc: 'ויזה כ.א.ל-י'
    creditCard: visaCal
  - desc: 'כרטיסי אשראי-י'
    creditCard: visaCal
scraper:
  parallel: true
  args: []